// Code generated by goctl. DO NOT EDIT!
// Source: agent.proto

package server

import (
	"context"

	"github.com/hongyuxuan/lizardcd/agent/internal/logic"
	"github.com/hongyuxuan/lizardcd/agent/internal/svc"
	"github.com/hongyuxuan/lizardcd/agent/types/agent"
)

type LizardAgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedLizardAgentServer
}

func NewLizardAgentServer(svcCtx *svc.ServiceContext) *LizardAgentServer {
	return &LizardAgentServer{
		svcCtx: svcCtx,
	}
}

// kubernetes
func (s *LizardAgentServer) GetNamespaces(ctx context.Context, in *agent.LabelSelector) (*agent.Response, error) {
	l := logic.NewGetNamespacesLogic(ctx, s.svcCtx)
	return l.GetNamespaces(in)
}

func (s *LizardAgentServer) ListResource(ctx context.Context, in *agent.ListResourceRequest) (*agent.Response, error) {
	l := logic.NewListResourceLogic(ctx, s.svcCtx)
	return l.ListResource(in)
}

func (s *LizardAgentServer) GetResource(ctx context.Context, in *agent.GetResourceRequest) (*agent.Response, error) {
	l := logic.NewGetResourceLogic(ctx, s.svcCtx)
	return l.GetResource(in)
}

func (s *LizardAgentServer) DeleteResource(ctx context.Context, in *agent.DeleteResourceRequest) (*agent.Response, error) {
	l := logic.NewDeleteResourceLogic(ctx, s.svcCtx)
	return l.DeleteResource(in)
}

func (s *LizardAgentServer) PatchWorkload(ctx context.Context, in *agent.PatchWorkloadRequest) (*agent.Response, error) {
	l := logic.NewPatchWorkloadLogic(ctx, s.svcCtx)
	return l.PatchWorkload(in)
}

func (s *LizardAgentServer) RolloutWorkload(ctx context.Context, in *agent.PatchWorkloadRequest) (*agent.Response, error) {
	l := logic.NewRolloutWorkloadLogic(ctx, s.svcCtx)
	return l.RolloutWorkload(in)
}

func (s *LizardAgentServer) ScaleWorkload(ctx context.Context, in *agent.ScaleRequest) (*agent.Response, error) {
	l := logic.NewScaleWorkloadLogic(ctx, s.svcCtx)
	return l.ScaleWorkload(in)
}

func (s *LizardAgentServer) GetEvent(ctx context.Context, in *agent.GetEventRequest) (*agent.Response, error) {
	l := logic.NewGetEventLogic(ctx, s.svcCtx)
	return l.GetEvent(in)
}

func (s *LizardAgentServer) GetResourceStatus(ctx context.Context, in *agent.GetResourceRequest) (*agent.Response, error) {
	l := logic.NewGetResourceStatusLogic(ctx, s.svcCtx)
	return l.GetResourceStatus(in)
}

func (s *LizardAgentServer) DeleteYaml(ctx context.Context, in *agent.YamlRequest) (*agent.Response, error) {
	l := logic.NewDeleteYamlLogic(ctx, s.svcCtx)
	return l.DeleteYaml(in)
}

func (s *LizardAgentServer) ApplyYaml(ctx context.Context, in *agent.YamlRequest) (*agent.Response, error) {
	l := logic.NewApplyYamlLogic(ctx, s.svcCtx)
	return l.ApplyYaml(in)
}

func (s *LizardAgentServer) GetYaml(ctx context.Context, in *agent.GetYamlRequest) (*agent.YamlResponse, error) {
	l := logic.NewGetYamlLogic(ctx, s.svcCtx)
	return l.GetYaml(in)
}

func (s *LizardAgentServer) GetWorkloadPod(ctx context.Context, in *agent.GetResourceRequest) (*agent.Response, error) {
	l := logic.NewGetWorkloadPodLogic(ctx, s.svcCtx)
	return l.GetWorkloadPod(in)
}

func (s *LizardAgentServer) GetWorkloadReplicas(ctx context.Context, in *agent.ReplicaRequest) (*agent.Response, error) {
	l := logic.NewGetWorkloadReplicasLogic(ctx, s.svcCtx)
	return l.GetWorkloadReplicas(in)
}

func (s *LizardAgentServer) GetWorkloadImages(ctx context.Context, in *agent.ReplicaRequest) (*agent.Response, error) {
	l := logic.NewGetWorkloadImagesLogic(ctx, s.svcCtx)
	return l.GetWorkloadImages(in)
}

func (s *LizardAgentServer) GetWorkloadQuota(ctx context.Context, in *agent.GetResourceRequest) (*agent.Response, error) {
	l := logic.NewGetWorkloadQuotaLogic(ctx, s.svcCtx)
	return l.GetWorkloadQuota(in)
}

func (s *LizardAgentServer) GetPodLog(ctx context.Context, in *agent.PodLogRequest) (*agent.YamlResponse, error) {
	l := logic.NewGetPodLogLogic(ctx, s.svcCtx)
	return l.GetPodLog(in)
}

func (s *LizardAgentServer) GetPodLogFollow(in *agent.PodLogRequest, stream agent.LizardAgent_GetPodLogFollowServer) error {
	l := logic.NewGetPodLogFollowLogic(stream.Context(), s.svcCtx)
	return l.GetPodLogFollow(in, stream)
}

func (s *LizardAgentServer) SetPodHorizonAutoscaler(ctx context.Context, in *agent.HpaRequest) (*agent.Response, error) {
	l := logic.NewSetPodHorizonAutoscalerLogic(ctx, s.svcCtx)
	return l.SetPodHorizonAutoscaler(in)
}

func (s *LizardAgentServer) GetPodHorizonAutoscaler(ctx context.Context, in *agent.PatchWorkloadRequest) (*agent.Response, error) {
	l := logic.NewGetPodHorizonAutoscalerLogic(ctx, s.svcCtx)
	return l.GetPodHorizonAutoscaler(in)
}

func (s *LizardAgentServer) RunCommandInPod(stream agent.LizardAgent_RunCommandInPodServer) error {
	l := logic.NewRunCommandInPodLogic(stream.Context(), s.svcCtx)
	return l.RunCommandInPod(stream)
}

func (s *LizardAgentServer) PatchConfigmap(ctx context.Context, in *agent.PatchConfigmapRequest) (*agent.Response, error) {
	l := logic.NewPatchConfigmapLogic(ctx, s.svcCtx)
	return l.PatchConfigmap(in)
}

// istio
func (s *LizardAgentServer) CreateDestinationRule(ctx context.Context, in *agent.IstioCreateRequest) (*agent.Response, error) {
	l := logic.NewCreateDestinationRuleLogic(ctx, s.svcCtx)
	return l.CreateDestinationRule(in)
}

func (s *LizardAgentServer) PatchDestinationRule(ctx context.Context, in *agent.IstioPatchRequest) (*agent.Response, error) {
	l := logic.NewPatchDestinationRuleLogic(ctx, s.svcCtx)
	return l.PatchDestinationRule(in)
}

func (s *LizardAgentServer) ListDestinationRule(ctx context.Context, in *agent.ListResourceRequest) (*agent.Response, error) {
	l := logic.NewListDestinationRuleLogic(ctx, s.svcCtx)
	return l.ListDestinationRule(in)
}

func (s *LizardAgentServer) GetDestinationRule(ctx context.Context, in *agent.IstioGetRequest) (*agent.Response, error) {
	l := logic.NewGetDestinationRuleLogic(ctx, s.svcCtx)
	return l.GetDestinationRule(in)
}

func (s *LizardAgentServer) DeleteDestinationRule(ctx context.Context, in *agent.IstioGetRequest) (*agent.Response, error) {
	l := logic.NewDeleteDestinationRuleLogic(ctx, s.svcCtx)
	return l.DeleteDestinationRule(in)
}

func (s *LizardAgentServer) CreateVirtualService(ctx context.Context, in *agent.IstioCreateRequest) (*agent.Response, error) {
	l := logic.NewCreateVirtualServiceLogic(ctx, s.svcCtx)
	return l.CreateVirtualService(in)
}

func (s *LizardAgentServer) PatchVirtualService(ctx context.Context, in *agent.IstioPatchRequest) (*agent.Response, error) {
	l := logic.NewPatchVirtualServiceLogic(ctx, s.svcCtx)
	return l.PatchVirtualService(in)
}

func (s *LizardAgentServer) ListVirtualService(ctx context.Context, in *agent.ListResourceRequest) (*agent.Response, error) {
	l := logic.NewListVirtualServiceLogic(ctx, s.svcCtx)
	return l.ListVirtualService(in)
}

func (s *LizardAgentServer) GetVirtualService(ctx context.Context, in *agent.IstioGetRequest) (*agent.Response, error) {
	l := logic.NewGetVirtualServiceLogic(ctx, s.svcCtx)
	return l.GetVirtualService(in)
}

func (s *LizardAgentServer) DeleteVirtualService(ctx context.Context, in *agent.IstioGetRequest) (*agent.Response, error) {
	l := logic.NewDeleteVirtualServiceLogic(ctx, s.svcCtx)
	return l.DeleteVirtualService(in)
}

func (s *LizardAgentServer) PatchGateway(ctx context.Context, in *agent.IstioPatchRequest) (*agent.Response, error) {
	l := logic.NewPatchGatewayLogic(ctx, s.svcCtx)
	return l.PatchGateway(in)
}

func (s *LizardAgentServer) ListGateway(ctx context.Context, in *agent.ListResourceRequest) (*agent.Response, error) {
	l := logic.NewListGatewayLogic(ctx, s.svcCtx)
	return l.ListGateway(in)
}

func (s *LizardAgentServer) GetGateway(ctx context.Context, in *agent.IstioGetRequest) (*agent.Response, error) {
	l := logic.NewGetGatewayLogic(ctx, s.svcCtx)
	return l.GetGateway(in)
}

func (s *LizardAgentServer) DeleteGateway(ctx context.Context, in *agent.IstioGetRequest) (*agent.Response, error) {
	l := logic.NewDeleteGatewayLogic(ctx, s.svcCtx)
	return l.DeleteGateway(in)
}

// tekton
func (s *LizardAgentServer) ListTektonResource(ctx context.Context, in *agent.TektonListRequest) (*agent.Response, error) {
	l := logic.NewListTektonResourceLogic(ctx, s.svcCtx)
	return l.ListTektonResource(in)
}

func (s *LizardAgentServer) GetTektonResource(ctx context.Context, in *agent.TektonYamlRequest) (*agent.Response, error) {
	l := logic.NewGetTektonResourceLogic(ctx, s.svcCtx)
	return l.GetTektonResource(in)
}

func (s *LizardAgentServer) PatchTektonResource(ctx context.Context, in *agent.TektonPatchRequest) (*agent.Response, error) {
	l := logic.NewPatchTektonResourceLogic(ctx, s.svcCtx)
	return l.PatchTektonResource(in)
}

func (s *LizardAgentServer) GetTektonYaml(ctx context.Context, in *agent.TektonYamlRequest) (*agent.YamlResponse, error) {
	l := logic.NewGetTektonYamlLogic(ctx, s.svcCtx)
	return l.GetTektonYaml(in)
}

func (s *LizardAgentServer) ApplyTektonResource(ctx context.Context, in *agent.TektonYamlRequest) (*agent.Response, error) {
	l := logic.NewApplyTektonResourceLogic(ctx, s.svcCtx)
	return l.ApplyTektonResource(in)
}

func (s *LizardAgentServer) DeleteTektonResource(ctx context.Context, in *agent.TektonYamlRequest) (*agent.Response, error) {
	l := logic.NewDeleteTektonResourceLogic(ctx, s.svcCtx)
	return l.DeleteTektonResource(in)
}

func (s *LizardAgentServer) GetTektonEndpoint(ctx context.Context, in *agent.TektonEndpointRequest) (*agent.Response, error) {
	l := logic.NewGetTektonEndpointLogic(ctx, s.svcCtx)
	return l.GetTektonEndpoint(in)
}

// helm
func (s *LizardAgentServer) HelmUpdateRepo(ctx context.Context, in *agent.HelmEntriesRequest) (*agent.Response, error) {
	l := logic.NewHelmUpdateRepoLogic(ctx, s.svcCtx)
	return l.HelmUpdateRepo(in)
}

func (s *LizardAgentServer) HelmInstallChart(ctx context.Context, in *agent.HelmInstallChartRequest) (*agent.Response, error) {
	l := logic.NewHelmInstallChartLogic(ctx, s.svcCtx)
	return l.HelmInstallChart(in)
}

func (s *LizardAgentServer) HelmUninstallChart(ctx context.Context, in *agent.HelmInstallChartRequest) (*agent.Response, error) {
	l := logic.NewHelmUninstallChartLogic(ctx, s.svcCtx)
	return l.HelmUninstallChart(in)
}

func (s *LizardAgentServer) HelmUpgradeChart(ctx context.Context, in *agent.HelmInstallChartRequest) (*agent.Response, error) {
	l := logic.NewHelmUpgradeChartLogic(ctx, s.svcCtx)
	return l.HelmUpgradeChart(in)
}

func (s *LizardAgentServer) HelmListReleases(ctx context.Context, in *agent.ListReleasesRequest) (*agent.Response, error) {
	l := logic.NewHelmListReleasesLogic(ctx, s.svcCtx)
	return l.HelmListReleases(in)
}

func (s *LizardAgentServer) HelmGetValues(ctx context.Context, in *agent.ListReleasesRequest) (*agent.Response, error) {
	l := logic.NewHelmGetValuesLogic(ctx, s.svcCtx)
	return l.HelmGetValues(in)
}

func (s *LizardAgentServer) HelmReleaseHistory(ctx context.Context, in *agent.ListReleasesRequest) (*agent.Response, error) {
	l := logic.NewHelmReleaseHistoryLogic(ctx, s.svcCtx)
	return l.HelmReleaseHistory(in)
}

func (s *LizardAgentServer) HelmRollback(ctx context.Context, in *agent.HelmInstallChartRequest) (*agent.Response, error) {
	l := logic.NewHelmRollbackLogic(ctx, s.svcCtx)
	return l.HelmRollback(in)
}

// vm deploy
func (s *LizardAgentServer) VmDeploy(ctx context.Context, in *agent.VmDeployRequest) (*agent.Response, error) {
	l := logic.NewVmDeployLogic(ctx, s.svcCtx)
	return l.VmDeploy(in)
}

func (s *LizardAgentServer) VmHealthCheck(ctx context.Context, in *agent.VmHealthCheckRequest) (*agent.Response, error) {
	l := logic.NewVmHealthCheckLogic(ctx, s.svcCtx)
	return l.VmHealthCheck(in)
}

func (s *LizardAgentServer) RunCommand(in *agent.RunCommandRequest, stream agent.LizardAgent_RunCommandServer) error {
	l := logic.NewRunCommandLogic(stream.Context(), s.svcCtx)
	return l.RunCommand(in, stream)
}

func (s *LizardAgentServer) DownloadFile(in *agent.FileRequest, stream agent.LizardAgent_DownloadFileServer) error {
	l := logic.NewDownloadFileLogic(stream.Context(), s.svcCtx)
	return l.DownloadFile(in, stream)
}

// docker deploy
func (s *LizardAgentServer) DockerDeploy(ctx context.Context, in *agent.DockerDeployRequest) (*agent.Response, error) {
	l := logic.NewDockerDeployLogic(ctx, s.svcCtx)
	return l.DockerDeploy(in)
}

func (s *LizardAgentServer) DockerCheck(ctx context.Context, in *agent.DockerDeployRequest) (*agent.Response, error) {
	l := logic.NewDockerCheckLogic(ctx, s.svcCtx)
	return l.DockerCheck(in)
}
