// Code generated by goctl. DO NOT EDIT!
// Source: agent.proto

package lizardagent

import (
	"context"

	"github.com/hongyuxuan/lizardcd/agent/types/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeleteResourceRequest   = agent.DeleteResourceRequest
	DockerDeployRequest     = agent.DockerDeployRequest
	FileRequest             = agent.FileRequest
	GetEventRequest         = agent.GetEventRequest
	GetResourceRequest      = agent.GetResourceRequest
	GetYamlRequest          = agent.GetYamlRequest
	HelmEntriesRequest      = agent.HelmEntriesRequest
	HelmInstallChartRequest = agent.HelmInstallChartRequest
	HpaRequest              = agent.HpaRequest
	IstioCreateRequest      = agent.IstioCreateRequest
	IstioGetRequest         = agent.IstioGetRequest
	IstioPatchRequest       = agent.IstioPatchRequest
	LabelSelector           = agent.LabelSelector
	ListReleasesRequest     = agent.ListReleasesRequest
	ListResourceRequest     = agent.ListResourceRequest
	PatchConfigmapRequest   = agent.PatchConfigmapRequest
	PatchWorkloadRequest    = agent.PatchWorkloadRequest
	PodCommandRequest       = agent.PodCommandRequest
	PodLogRequest           = agent.PodLogRequest
	ReplicaRequest          = agent.ReplicaRequest
	Response                = agent.Response
	RunCommandRequest       = agent.RunCommandRequest
	ScaleRequest            = agent.ScaleRequest
	TektonEndpointRequest   = agent.TektonEndpointRequest
	TektonListRequest       = agent.TektonListRequest
	TektonPatchRequest      = agent.TektonPatchRequest
	TektonYamlRequest       = agent.TektonYamlRequest
	VmDeployRequest         = agent.VmDeployRequest
	VmHealthCheckRequest    = agent.VmHealthCheckRequest
	YamlRequest             = agent.YamlRequest
	YamlResponse            = agent.YamlResponse

	LizardAgent interface {
		// kubernetes
		GetNamespaces(ctx context.Context, in *LabelSelector, opts ...grpc.CallOption) (*Response, error)
		ListResource(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error)
		GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error)
		DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*Response, error)
		PatchWorkload(ctx context.Context, in *PatchWorkloadRequest, opts ...grpc.CallOption) (*Response, error)
		RolloutWorkload(ctx context.Context, in *PatchWorkloadRequest, opts ...grpc.CallOption) (*Response, error)
		ScaleWorkload(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*Response, error)
		GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Response, error)
		GetResourceStatus(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error)
		DeleteYaml(ctx context.Context, in *YamlRequest, opts ...grpc.CallOption) (*Response, error)
		ApplyYaml(ctx context.Context, in *YamlRequest, opts ...grpc.CallOption) (*Response, error)
		GetYaml(ctx context.Context, in *GetYamlRequest, opts ...grpc.CallOption) (*YamlResponse, error)
		GetWorkloadPod(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error)
		GetWorkloadReplicas(ctx context.Context, in *ReplicaRequest, opts ...grpc.CallOption) (*Response, error)
		GetWorkloadImages(ctx context.Context, in *ReplicaRequest, opts ...grpc.CallOption) (*Response, error)
		GetWorkloadQuota(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error)
		GetPodLog(ctx context.Context, in *PodLogRequest, opts ...grpc.CallOption) (*YamlResponse, error)
		GetPodLogFollow(ctx context.Context, in *PodLogRequest, opts ...grpc.CallOption) (agent.LizardAgent_GetPodLogFollowClient, error)
		SetPodHorizonAutoscaler(ctx context.Context, in *HpaRequest, opts ...grpc.CallOption) (*Response, error)
		GetPodHorizonAutoscaler(ctx context.Context, in *PatchWorkloadRequest, opts ...grpc.CallOption) (*Response, error)
		RunCommandInPod(ctx context.Context, opts ...grpc.CallOption) (agent.LizardAgent_RunCommandInPodClient, error)
		PatchConfigmap(ctx context.Context, in *PatchConfigmapRequest, opts ...grpc.CallOption) (*Response, error)
		// istio
		CreateDestinationRule(ctx context.Context, in *IstioCreateRequest, opts ...grpc.CallOption) (*Response, error)
		PatchDestinationRule(ctx context.Context, in *IstioPatchRequest, opts ...grpc.CallOption) (*Response, error)
		ListDestinationRule(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error)
		GetDestinationRule(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error)
		DeleteDestinationRule(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error)
		CreateVirtualService(ctx context.Context, in *IstioCreateRequest, opts ...grpc.CallOption) (*Response, error)
		PatchVirtualService(ctx context.Context, in *IstioPatchRequest, opts ...grpc.CallOption) (*Response, error)
		ListVirtualService(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error)
		GetVirtualService(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error)
		DeleteVirtualService(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error)
		PatchGateway(ctx context.Context, in *IstioPatchRequest, opts ...grpc.CallOption) (*Response, error)
		ListGateway(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error)
		GetGateway(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error)
		DeleteGateway(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error)
		// tekton
		ListTektonResource(ctx context.Context, in *TektonListRequest, opts ...grpc.CallOption) (*Response, error)
		GetTektonResource(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*Response, error)
		PatchTektonResource(ctx context.Context, in *TektonPatchRequest, opts ...grpc.CallOption) (*Response, error)
		GetTektonYaml(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*YamlResponse, error)
		ApplyTektonResource(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*Response, error)
		DeleteTektonResource(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*Response, error)
		GetTektonEndpoint(ctx context.Context, in *TektonEndpointRequest, opts ...grpc.CallOption) (*Response, error)
		// helm
		HelmUpdateRepo(ctx context.Context, in *HelmEntriesRequest, opts ...grpc.CallOption) (*Response, error)
		HelmInstallChart(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error)
		HelmUninstallChart(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error)
		HelmUpgradeChart(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error)
		HelmListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*Response, error)
		HelmGetValues(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*Response, error)
		HelmReleaseHistory(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*Response, error)
		HelmRollback(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error)
		// vm deploy
		VmDeploy(ctx context.Context, in *VmDeployRequest, opts ...grpc.CallOption) (*Response, error)
		VmHealthCheck(ctx context.Context, in *VmHealthCheckRequest, opts ...grpc.CallOption) (*Response, error)
		RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (agent.LizardAgent_RunCommandClient, error)
		DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (agent.LizardAgent_DownloadFileClient, error)
		// docker deploy
		DockerDeploy(ctx context.Context, in *DockerDeployRequest, opts ...grpc.CallOption) (*Response, error)
		DockerCheck(ctx context.Context, in *DockerDeployRequest, opts ...grpc.CallOption) (*Response, error)
	}

	defaultLizardAgent struct {
		cli zrpc.Client
	}
)

func NewLizardAgent(cli zrpc.Client) LizardAgent {
	return &defaultLizardAgent{
		cli: cli,
	}
}

// kubernetes
func (m *defaultLizardAgent) GetNamespaces(ctx context.Context, in *LabelSelector, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetNamespaces(ctx, in, opts...)
}

func (m *defaultLizardAgent) ListResource(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ListResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DeleteResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) PatchWorkload(ctx context.Context, in *PatchWorkloadRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.PatchWorkload(ctx, in, opts...)
}

func (m *defaultLizardAgent) RolloutWorkload(ctx context.Context, in *PatchWorkloadRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.RolloutWorkload(ctx, in, opts...)
}

func (m *defaultLizardAgent) ScaleWorkload(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ScaleWorkload(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetEvent(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetResourceStatus(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetResourceStatus(ctx, in, opts...)
}

func (m *defaultLizardAgent) DeleteYaml(ctx context.Context, in *YamlRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DeleteYaml(ctx, in, opts...)
}

func (m *defaultLizardAgent) ApplyYaml(ctx context.Context, in *YamlRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ApplyYaml(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetYaml(ctx context.Context, in *GetYamlRequest, opts ...grpc.CallOption) (*YamlResponse, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetYaml(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetWorkloadPod(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetWorkloadPod(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetWorkloadReplicas(ctx context.Context, in *ReplicaRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetWorkloadReplicas(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetWorkloadImages(ctx context.Context, in *ReplicaRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetWorkloadImages(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetWorkloadQuota(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetWorkloadQuota(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetPodLog(ctx context.Context, in *PodLogRequest, opts ...grpc.CallOption) (*YamlResponse, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetPodLog(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetPodLogFollow(ctx context.Context, in *PodLogRequest, opts ...grpc.CallOption) (agent.LizardAgent_GetPodLogFollowClient, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetPodLogFollow(ctx, in, opts...)
}

func (m *defaultLizardAgent) SetPodHorizonAutoscaler(ctx context.Context, in *HpaRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.SetPodHorizonAutoscaler(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetPodHorizonAutoscaler(ctx context.Context, in *PatchWorkloadRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetPodHorizonAutoscaler(ctx, in, opts...)
}

func (m *defaultLizardAgent) RunCommandInPod(ctx context.Context, opts ...grpc.CallOption) (agent.LizardAgent_RunCommandInPodClient, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.RunCommandInPod(ctx, opts...)
}

func (m *defaultLizardAgent) PatchConfigmap(ctx context.Context, in *PatchConfigmapRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.PatchConfigmap(ctx, in, opts...)
}

// istio
func (m *defaultLizardAgent) CreateDestinationRule(ctx context.Context, in *IstioCreateRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.CreateDestinationRule(ctx, in, opts...)
}

func (m *defaultLizardAgent) PatchDestinationRule(ctx context.Context, in *IstioPatchRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.PatchDestinationRule(ctx, in, opts...)
}

func (m *defaultLizardAgent) ListDestinationRule(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ListDestinationRule(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetDestinationRule(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetDestinationRule(ctx, in, opts...)
}

func (m *defaultLizardAgent) DeleteDestinationRule(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DeleteDestinationRule(ctx, in, opts...)
}

func (m *defaultLizardAgent) CreateVirtualService(ctx context.Context, in *IstioCreateRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.CreateVirtualService(ctx, in, opts...)
}

func (m *defaultLizardAgent) PatchVirtualService(ctx context.Context, in *IstioPatchRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.PatchVirtualService(ctx, in, opts...)
}

func (m *defaultLizardAgent) ListVirtualService(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ListVirtualService(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetVirtualService(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetVirtualService(ctx, in, opts...)
}

func (m *defaultLizardAgent) DeleteVirtualService(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DeleteVirtualService(ctx, in, opts...)
}

func (m *defaultLizardAgent) PatchGateway(ctx context.Context, in *IstioPatchRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.PatchGateway(ctx, in, opts...)
}

func (m *defaultLizardAgent) ListGateway(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ListGateway(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetGateway(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetGateway(ctx, in, opts...)
}

func (m *defaultLizardAgent) DeleteGateway(ctx context.Context, in *IstioGetRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DeleteGateway(ctx, in, opts...)
}

// tekton
func (m *defaultLizardAgent) ListTektonResource(ctx context.Context, in *TektonListRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ListTektonResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetTektonResource(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetTektonResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) PatchTektonResource(ctx context.Context, in *TektonPatchRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.PatchTektonResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetTektonYaml(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*YamlResponse, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetTektonYaml(ctx, in, opts...)
}

func (m *defaultLizardAgent) ApplyTektonResource(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.ApplyTektonResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) DeleteTektonResource(ctx context.Context, in *TektonYamlRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DeleteTektonResource(ctx, in, opts...)
}

func (m *defaultLizardAgent) GetTektonEndpoint(ctx context.Context, in *TektonEndpointRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.GetTektonEndpoint(ctx, in, opts...)
}

// helm
func (m *defaultLizardAgent) HelmUpdateRepo(ctx context.Context, in *HelmEntriesRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmUpdateRepo(ctx, in, opts...)
}

func (m *defaultLizardAgent) HelmInstallChart(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmInstallChart(ctx, in, opts...)
}

func (m *defaultLizardAgent) HelmUninstallChart(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmUninstallChart(ctx, in, opts...)
}

func (m *defaultLizardAgent) HelmUpgradeChart(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmUpgradeChart(ctx, in, opts...)
}

func (m *defaultLizardAgent) HelmListReleases(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmListReleases(ctx, in, opts...)
}

func (m *defaultLizardAgent) HelmGetValues(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmGetValues(ctx, in, opts...)
}

func (m *defaultLizardAgent) HelmReleaseHistory(ctx context.Context, in *ListReleasesRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmReleaseHistory(ctx, in, opts...)
}

func (m *defaultLizardAgent) HelmRollback(ctx context.Context, in *HelmInstallChartRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.HelmRollback(ctx, in, opts...)
}

// vm deploy
func (m *defaultLizardAgent) VmDeploy(ctx context.Context, in *VmDeployRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.VmDeploy(ctx, in, opts...)
}

func (m *defaultLizardAgent) VmHealthCheck(ctx context.Context, in *VmHealthCheckRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.VmHealthCheck(ctx, in, opts...)
}

func (m *defaultLizardAgent) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (agent.LizardAgent_RunCommandClient, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.RunCommand(ctx, in, opts...)
}

func (m *defaultLizardAgent) DownloadFile(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (agent.LizardAgent_DownloadFileClient, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DownloadFile(ctx, in, opts...)
}

// docker deploy
func (m *defaultLizardAgent) DockerDeploy(ctx context.Context, in *DockerDeployRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DockerDeploy(ctx, in, opts...)
}

func (m *defaultLizardAgent) DockerCheck(ctx context.Context, in *DockerDeployRequest, opts ...grpc.CallOption) (*Response, error) {
	client := agent.NewLizardAgentClient(m.cli.Conn())
	return client.DockerCheck(ctx, in, opts...)
}
