// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	consul "github.com/hongyuxuan/lizardcd/server/internal/handler/consul"
	lizardcd "github.com/hongyuxuan/lizardcd/server/internal/handler/lizardcd"
	"github.com/hongyuxuan/lizardcd/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPatch,
				Path:    "/cluster/:cluster/namespace/:namespace/deployments/:workload_name",
				Handler: lizardcd.PatchDeploymentHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/cluster/:cluster/namespace/:namespace/statefulsets/:workload_name",
				Handler: lizardcd.PatchStatefulsetHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/cluster/:cluster/namespace/:namespace/deployments/:workload_name/rollout",
				Handler: lizardcd.RolloutDeploymentHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/cluster/:cluster/namespace/:namespace/statefulsets/:workload_name/rollout",
				Handler: lizardcd.RolloutStatefulsetHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/cluster/:cluster/namespace/:namespace/deployments/scale",
				Handler: lizardcd.ScaleDeploymentHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/cluster/:cluster/namespace/:namespace/statefulsets/scale",
				Handler: lizardcd.ScaleStatefulsetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cluster/:cluster/namespace/:namespace/:resource_type/:resource_name/yaml",
				Handler: lizardcd.GetYamlHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/cluster/:cluster/namespace/:namespace/apply/yaml",
				Handler: lizardcd.PatchYamlHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cluster/:cluster/namespace/:namespace/deployments",
				Handler: lizardcd.ListDeploymentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cluster/:cluster/namespace/:namespace/statefulsets",
				Handler: lizardcd.ListStatefulsetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cluster/:cluster/namespace/:namespace/deployments/:workload_name/pods",
				Handler: lizardcd.DeploymentPodsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cluster/:cluster/namespace/:namespace/statefulsets/:workload_name/pods",
				Handler: lizardcd.StatefulsetPodsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cluster/:cluster/namespace/:namespace/pods/:pod_name/events",
				Handler: lizardcd.PodEventsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/lizardcd"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/services",
				Handler: consul.ListservicesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/services/:service_name",
				Handler: consul.GetserviceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/clusters",
				Handler: consul.ListclustersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/consul"),
	)
}
